### ISSUE TITLE
Retrieve out of cache doesn't work

### ISSUE THREAD

**Issue by IOIO72** [jopemachine/alfred-evernote-workflow#56]
The retrieval out of the cache gives the following error:

```bash
/usr/local/lib/node_modules/alfred-evernote-workflow/search_content/htmlCacheLog.json:1
SyntaxError: /usr/local/lib/node_modules/alfred-evernote-workflow/search_content/htmlCacheLog.json: Unexpected number in JSON at position 46
    at parse (<anonymous>)
    at Generator.next (<anonymous>)
-
alfred-evernote-workflow 0.7.9
Alfred 4.1
darwin 19.6.0
```

### Your environment

*   **OS**: macOS 10.15.6
*   **Packages**: 
*   **Env**: Node 14.9.0; npm 6.14.8

### Steps to reproduce

1. Save Cache
2. Wait for save completion
3. Use any search (i.e. `ent`)
4. Results lead to the error mentioned above

### Expected behaviour

List of notes

### Actual behaviour

Error message

**Comment by jopemachine** [comment]
Thanks for reporting a bug.
 
Could you send me the htmlCacheLog.json file to `gravity95@gmail.com`?
 
I think I need to look into your htmlCacheLog.json to grasp what has happened.
 
 
-----Original Message-----

**Comment by jopemachine** [comment]
Could you check if this issue still occurs in 0.8.0?

I've changed the way that the json file is saved in the Applescript.

**Comment by IOIO72** [comment]
> Could you check if this issue still occurs in 0.8.0?
> 
> I've changed the way that the json file is saved in the Applescript.

You fixed it! Great! Thanks! 👍
