### ISSUE TITLE
Can't open Note

### ISSUE THREAD

**Issue by Paul-creator** [jopemachine/alfred-evernote-workflow#79]
When I run `ens <querry>` the results are right. But when I want to open one with pressing `enter` an error in the workflowdebugger is thrown:
`[16:16:24.077] ERROR: alfred-evernote-workflow[Run Script] evernote:///view/230916389/s449/105847e3-30a6-dd29-8c20-b7462699d8b2/105847e3-30a6-dd29-8c20-b7462699d8b2/
`
The specific failing script is: `openNoteWithNotelink.scpt`:
```
// Applescript (Javascript)

function run(input) {

  if (!input) input = "";

  var evernote = Application('Evernote');
  evernote.activate();

  var query = input[0];
  
  console.log(query)

  const hasSpecialBracket = /\$\{.*\}/;

  if(hasSpecialBracket.test(query)) {
    query = input[1];
  }

  var note = evernote.findNote(query);
  evernote.openNoteWindow({ with: note });

}
```

When I try to run it in the `Script Editor` the following error is thrown:
`Error -1708: Message not understood.`

**Comment by jopemachine** [comment]
```
function run(input) {

  if (!input) input = "";

  var evernote = Application('Evernote');
  evernote.activate();

  var query = "evernote:///view/230916389/s449/105847e3-30a6-dd29-8c20-b7462699d8b2/105847e3-30a6-dd29-8c20-b7462699d8b2/";
  
  console.log(query)

  const hasSpecialBracket = /\$\{.*\}/;

  if(hasSpecialBracket.test(query)) {
    query = input[1];
  }

  var note = evernote.findNote(query);
  evernote.openNoteWindow({ with: note });
}

```

Could you try the above code in your `Script Editor`?

Does your note open?

**Comment by Paul-creator** [comment]
As I already wrote:
When I try to run it in the `Script Editor` the following error is thrown:
`Error -1708: Message not understood.`

No, it doesn’t open the note.

**Comment by jopemachine** [comment]
> As I already wrote:
> When I try to run it in the `Script Editor` the following error is thrown:
> `Error -1708: Message not understood.`
> 
> No, it doesn’t open the note.

I had seen your comment.

The code I commented is not same with this workflow's script.

If your script editor throws same error though, please let me know.  (And pls let me know your mac version too)

**Comment by Paul-creator** [comment]
I started working now. (The workflow works and the scripts both open Evernode).
Maybe I messed it up 2 days ago calling `en > savecache` and `en > clearcache` several times.

**Comment by jopemachine** [comment]
> I started working now. (The workflow works and the scripts both open Evernode).
> Maybe I messed it up 2 days ago calling `en > savecache` and `en > clearcache` several times.

I'm happy to hear you resolve the issue.
