### ISSUE TITLE
[Installation issue] npm permission issue

### ISSUE THREAD

**Issue by jopemachine** [jopemachine/alfred-evernote-workflow#8]
## Issue

```
npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! alfred-evernote-workflow@0.1.8 postinstall: `alfy-init`

npm ERR! Exit status 1

npm ERR! 

npm ERR! Failed at the alfred-evernote-workflow@0.1.8 postinstall script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.



npm ERR! A complete log of this run can be found in:

npm ERR!     /Users/flo/.npm/_logs/2020-07-14T19_03_26_308Z-debug.log

```

**Comment by jopemachine** [comment]
Permission error. 

By executing below commands, it can be resolved.

```
sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}
```


Ref : https://stackoverflow.com/questions/47252451/permission-denied-when-installing-npm-modules-in-osx

**Comment by hjm79** [comment]
[2020-08-04T10_04_01_866Z-debug.log](https://github.com/jopemachine/alfred-evernote-workflow/files/5021449/2020-08-04T10_04_01_866Z-debug.log)

무엇이 문제일까요??

**Comment by jopemachine** [comment]
> [2020-08-04T10_04_01_866Z-debug.log](https://github.com/jopemachine/alfred-evernote-workflow/files/5021449/2020-08-04T10_04_01_866Z-debug.log)
> 
> 무엇이 문제일까요??

https://github.com/jopemachine/alfred-evernote-workflow/issues/42

위 방법대로 해 보시겠어요??

여전히 에러가 나면 알려주세요!

**Comment by hjm79** [comment]
[2020-08-04T23_45_29_712Z-debug.log](https://github.com/jopemachine/alfred-evernote-workflow/files/5025342/2020-08-04T23_45_29_712Z-debug.log)

npm ERR! code EUIDLOOKUP
npm ERR! errno 1
npm ERR! lifecycle EPERM, Operation not permitted
npm ERR!
npm ERR! Failed to look up the user/group for running scripts.
npm ERR!
npm ERR! Try again with a different --user or --group settings, or
npm ERR! run with --unsafe-perm to execute scripts as root.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hjm79/.npm/_logs/2020-08-04T23_49_12_386Z-debug.log


에러 계속 납니다.  

그래소 그냥
압축풀고 워크플로우 폴더에 복사해서 사용해봤습니다.  
 에버노트에서 토큰확인해서 설정까지 했는데 작동이 안되더군요 ens 키워드 넣으면 반응이 없습니다.   

그리고 커맨드 방식이 아닌 workflow 파일로 공유하지는 않으시나요? 
기존 에버노트 플러그인 미리보기가 안되어 넘어오려고 합니다.  미리보기도 가능한지 궁금합니다.

**Comment by jopemachine** [comment]
> [2020-08-04T23_45_29_712Z-debug.log](https://github.com/jopemachine/alfred-evernote-workflow/files/5025342/2020-08-04T23_45_29_712Z-debug.log)
> 
> npm ERR! code EUIDLOOKUP
> npm ERR! errno 1
> npm ERR! lifecycle EPERM, Operation not permitted
> npm ERR!
> npm ERR! Failed to look up the user/group for running scripts.
> npm ERR!
> npm ERR! Try again with a different --user or --group settings, or
> npm ERR! run with --unsafe-perm to execute scripts as root.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /Users/hjm79/.npm/_logs/2020-08-04T23_49_12_386Z-debug.log
> 
> 에러 계속 납니다.
> 
> 그래소 그냥
> 압축풀고 워크플로우 폴더에 복사해서 사용해봤습니다.
> 에버노트에서 토큰확인해서 설정까지 했는데 작동이 안되더군요 ens 키워드 넣으면 반응이 없습니다.
> 
> 그리고 커맨드 방식이 아닌 workflow 파일로 공유하지는 않으시나요?
> 기존 에버노트 플러그인 미리보기가 안되어 넘어오려고 합니다. 미리보기도 가능한지 궁금합니다.

1. 혹시 npm i -g 명령어로 다른 패키지는 잘 설치가 되시나요?

2. 아직은 workflow 파일 형태로 배포하고 있지 않습니다만, 가까운 시일 내에 workflow 파일로도 만들어 업로드할 생각입니다. 
이렇게 설치하는 경우에도, `en > savecache` 입력으로 html 및 리소스 파일들을 export해서 미리보기를 사용할 수 있습니다.

**Comment by jopemachine** [comment]
> [2020-08-04T23_45_29_712Z-debug.log](https://github.com/jopemachine/alfred-evernote-workflow/files/5025342/2020-08-04T23_45_29_712Z-debug.log)
> 
> npm ERR! code EUIDLOOKUP
> npm ERR! errno 1
> npm ERR! lifecycle EPERM, Operation not permitted
> npm ERR!
> npm ERR! Failed to look up the user/group for running scripts.
> npm ERR!
> npm ERR! Try again with a different --user or --group settings, or
> npm ERR! run with --unsafe-perm to execute scripts as root.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /Users/hjm79/.npm/_logs/2020-08-04T23_49_12_386Z-debug.log
> 
> 에러 계속 납니다.
> 
> 그래소 그냥
> 압축풀고 워크플로우 폴더에 복사해서 사용해봤습니다.
> 에버노트에서 토큰확인해서 설정까지 했는데 작동이 안되더군요 ens 키워드 넣으면 반응이 없습니다.
> 
> 그리고 커맨드 방식이 아닌 workflow 파일로 공유하지는 않으시나요?
> 기존 에버노트 플러그인 미리보기가 안되어 넘어오려고 합니다. 미리보기도 가능한지 궁금합니다.

workflow 파일 다운로드 링크: 
https://www.packal.org/workflow/alfred-evernote-workflow

**Comment by hjm79** [comment]
감사합니다. 작동 잘되네요!!  기존 에보노트에서 이걸로 갈아탔습니다.

미리보기도 잘되고!!   감사합니다.   이 게시글 블로그에 올려도 될까요????

**Comment by jopemachine** [comment]
> 감사합니다. 작동 잘되네요!! 기존 에보노트에서 이걸로 갈아탔습니다.
> 
> 미리보기도 잘되고!! 감사합니다. 이 게시글 블로그에 올려도 될까요????

넵, 올리셔도 됩니다!
