### ISSUE TITLE
Can not open the evernote note

### ISSUE THREAD

**Issue by imbutter** [jopemachine/alfred-evernote-workflow#82]
The Evernote version is 10.33.4-mac-mas-public (459002),
when I type the "ens" for search , eg:google ,Alfred shows a list ,but when type one list ,only open the Evernote application,can not open the note.

**Comment by jopemachine** [comment]
> The Evernote version is 10.33.4-mac-mas-public (459002),
> when I type the "ens" for search , eg:google ,Alfred shows a list ,but when type one list ,only open the Evernote application,can not open the note.

You can work this workflow only through Evernote's legacy version since Evernote discards applescript support.

**Comment by imbutter** [comment]
ok! thanks you!
